### ISSUE TITLE
Recommended glossary / reading?

### ISSUE THREAD

**Issue by busywhistling** [dt-developers/tadhack-2022#1]
Hi, is there a recommended glossary / reading for the technologies referenced in these APIs? (I can of course look them up on Google, but wanted to inquire first if you have a pointer)

**Comment by mariobodemann** [comment]
Hey,

I think a quite nice overview can be found here:

https://github.com/camaraproject/QualityOnDemand/blob/main/documentation/API_documentation/QoD_Stable_Bandwidth_API.md

Also the overarching organization https://github.com/camaraproject can probably be a good starting point for more information.
